### ISSUE TITLE
Confirm API design for read operations

### ISSUE THREAD

**Issue by ZaneBartlett1** [DartExplore/dallas-by-metro-backend#128]
These read operations are essential for building any kind of front end, and I think we should have four main endpoints for now.

# Base URL

`dallasbymetro.com/api/`

# Endpoints

## **GET:** `public/all`

Fetches all data points including Stations and their Points of Interest, grouped by Station.

**Request Parameters**

 - None

**Example Request**

`dallasbymetro.com/api/public/all`

<details>
<summary>Example Response</summary>

```json
{
  "stations": [
    {
      "stationId": 1,
      "name": "Mockingbird Station",
      "servedLines": ["Orange Line", "Red Line"],
      "latitude": 32.8481,
      "longitude": -96.7871,
      "pointsOfInterest": [
        {
          "poiId": 1,
          "name": "Meadows Museum",
          "latitude": 32.8481,
          "longitude": -96.7871,
          "walkingDistance": 7,
          "pic_url": "https://images.meadowsmuseum.com/museum.jpg",
          "type": "Museum",
          "amenities": [
            "Vegetarian Options",
            "Bike Parking",
            "Vegan Options"
          ]
        },
        {
          "poiId": 2,
          "name": "Greenville Avenue Pizza Company",
          "latitude": 32.8480,
          "longitude": -96.7872,
          "walkingDistance": 10,
          "pic_url": "https://images.greenvillepizzaco.com/restaurant.jpg",
          "type": "Restaurant",
          "amenities": [
            "Vegetarian Options",
            "Bike Parking",
            "Alcohol Options"
          ]
        }
      ]
    },
    {
      "stationId": 2,
      "name": "Cityplace/Uptown Station",
      "servedLines": ["Blue Line"],
      "latitude": 32.8482,
      "longitude": -96.7872,
      "pointsOfInterest": [
        {
          "poiId": 3,
          "name": "Uptown Theater",
          "latitude": 32.8482,
          "longitude": -96.7873,
          "walkingDistance": 6,
          "pic_url": "https://images.uptowntheater.com/theater.jpg",
          "type": "Theater",
          "amenities": [
            "Vegetarian Options",
            "Bike Parking",
            "Alcohol Options"
          ]
        },
        {
          "poiId": 4,
          "name": "Beyond Sushi",
          "latitude": 32.8484,
          "longitude": -96.7874,
          "walkingDistance": 10,
          "pic_url": "https://images.beyondsushi.com/restaurant.jpg",
          "type": "Restaurant",
          "amenities": [
            "Vegetarian Options",
            "Bike Parking"
          ]
        }
      ]
    }
  ]
}
```
</details>

## **GET:** `public/stations`

Fetches Station information, including served lines, rail travel time, Points of Interest (POIs), and the POIs' types, walking distances, images, and amenities. The result can be filtered by acceptable rail and walk times, and required POI amenities.

**Request Parameters**
 - current_station (optional): This is required in conjunction with rail_time. This is the starting station that will be used to calculate what stations are reachable from the current_station in the rail_time provided. 
 - rail_time (optional): The acceptable amount of time spent on rail travel (format as string, e.g., "30m" for 30 minutes, "2h" for 2 hours)
 - walk_time (optional): The acceptable amount of time spent walking (format as string, e.g., "10m" for 10 minutes, "1h" for 1 hour)
 - amenities (optional): The required amenities that need to be present at the POI (as a comma-separated list of strings)

**Example Request**

`dallasbymetro.com/api/public/stations?CurrentStation=1&RailTime=30m&WalkTime=10m&Amenities=Vegetarian%Options,Bike%Parking`

<details>
<summary>Example Response</summary>

```json
{
"stations": [
    {
      "stationId": 1,
      "name": "Mockingbird Station",
      "servedLines": ["Orange Line", "Red Line"],
      "pointsOfInterest": [
        {
          "poiId": 1,
          "name": "Meadows Museum",
          "type": "Museum",
          "walkingDistance": "7m",
          "pic_url": "https://images.meadowsmuseum.com/museum.jpg",
          "amenities": ["Vegetarian Options", "Bike Parking", "Vegan Options"]
        },
        {
          "poiId": 2,
          "name": "Greenville Avenue Pizza Company",
          "type": "Restaurant",
          "walkingDistance": "10m",
          "pic_url": "https://images.greenvillepizzaco.com/restaurant.jpg",
          "amenities": ["Vegetarian Options", "Bike Parking", "Alcohol Options"]
        }
      ]
    },
    {
      "stationId": 2,
      "name": "Cityplace/Uptown Station",
      "servedLines": ["Blue Line"],
      "railTravelTime": "30m",
      "pointsOfInterest": [
        {
          "poiId": 3,
          "name": "Uptown Theater",
          "type": "Theater",
          "walkingDistance": "6m",
          "pic_url": "https://images.uptowntheater.com/theater.jpg",
          "amenities": ["Vegetarian Options", "Bike Parking", "Alcohol Options"]
        },
        {
          "poiId": 4,
          "name": "Beyond Sushi",
          "type": "Restaurant",
          "walkingDistance": "10m",
          "pic_url": "https://images.beyondsushi.com/restaurant.jpg",
          "amenities": ["Vegetarian Options", "Bike Parking"]
        }
      ]
    }
  ]
}
```
</details>

## **GET:** `public/pois`

Fetches detailed information about Points of Interest (POIs) based on their ID(s).

**Request Parameters**

 - ID (required): The ID(s) of the Point(s) of Interest you would like all the information for (as a comma-separated list of integers)

**Example Request**

`dallasbymetro.com/api/public/pois?ID=1,2,3`

<details>
<summary>Example Response</summary>

```json
{
  "pointsOfInterest": [
    {
      "poiId": 1,
      "name": "Meadows Museum",
      "type": "Museum",
      "latitude": 32.8481,
      "longitude": -96.7871,
      "walkingDistance": "7m",
      "pic_url": "https://images.meadowsmuseum.com/museum.jpg",
      "amenities": ["Vegetarian Options", "Bike Parking", "Vegan Options"],
      "stationId": 1
    },
    {
      "poiId": 2,
      "name": "Greenville Avenue Pizza Company",
      "type": "Restaurant",
      "latitude": 32.8480,
      "longitude": -96.7872,
      "walkingDistance": "10m",
      "pic_url": "https://images.greenvillepizzaco.com/restaurant.jpg",
      "amenities": ["Vegetarian Options", "Bike Parking", "Alcohol Options"],
      "stationId": 1
    },
    {
      "poiId": 3,
      "name": "Uptown Theater",
      "type": "Theater",
      "latitude": 32.8482,
      "longitude": -96.7873,
      "walkingDistance": "6m",
      "pic_url": "https://images.uptowntheater.com/theater.jpg",
      "amenities": ["Vegetarian Options", "Bike Parking", "Alcohol Options"],
      "stationId": 3
    }
  ]
}
```
</details>

## **GET:** `public/line`

Fetches information about specific rail lines, including the Stations they connect to, based on the line color.

**Request Parameters**

 - Color (required): The color of the line you would like information for (as a string)

**Example Request**

`dallasbymetro.com/api/public/line?Color=BLUE`

<details>
<summary>Example Response</summary>

```json
{
  "line": {
    "color": "BLUE",
    "stations": [
      {
        "stationId": 1,
        "name": "Mockingbird Station"
      },
      {
        "stationId": 2,
        "name": "Cityplace/Uptown Station"
      }
    ]
  }
}
```
</details>

# Checklist 
- [x] /all
- [x] #175
- [x] #166
- [x] /line
- [x] #173

**Comment by ZaneBartlett1** [comment]
@gpennell and @Nightwing52 if you could please take a look at this and let me know thoughts. I think we should work on the first one as it's basically a giant JSON blob that gives Garrett something to work with, and if he shapes it like the rest of the API calls, then once we get those rolled out, they should be easily replaced later. 

Does that sound reasonable?

**Comment by Nightwing52** [comment]
One route that I would like to get now that I'm working on the frontend is _api/public/amenity_ which would simply return all the amenities. I need this so that on page load I can create the amenity selection table.

**Comment by ZaneBartlett1** [comment]
#164 is the pull request that merged /all in

**Comment by ZaneBartlett1** [comment]
Basically all of these are done and added (including /amenities, which will return all amenities) **except** /station. That one is much more tricky considering the amount of logic it requires.
