### ISSUE TITLE
Clean up create and update code.

### ISSUE THREAD

**Issue by Nightwing52** [DartExplore/dallas-by-metro-backend#149]
In the service layer we have a lot of code that looks like this for the create and update operations.

![image](https://github.com/DartExplore/dallas-by-metro-backend/assets/18405628/d48ebdd0-9136-40eb-8fb8-b4cec2b69a52)

I would like to convert this into a map of some sort for readability but also maintainability.

**Comment by Nightwing52** [comment]
Doing this in a map requires the use of the Field class which doing some research I'm really not a fan of. @ZaneBartlett1 we could make another DTO object for creation purposes but I'm probably okay with closing this issue. Looked closer at the codebase and there's only one time where this issue pops up.

**Comment by ZaneBartlett1** [comment]
Sounds good to me, also for referencing code - 
[Screencast from 06-16-2023 02:18:58 AM.webm](https://github.com/DartExplore/dallas-by-metro-backend/assets/85081861/8151f132-61a9-49fb-bf9b-39029e42a05f)



https://github.com/DartExplore/dallas-by-metro-backend/blob/1f451d69d0febb73bdd0bfa26b02f0461da895ac/mvnw#L46-L58

**Comment by Nightwing52** [comment]
Thanks for the tip! Yeah, I'm good to close this issue.
