### ISSUE TITLE
/station

### ISSUE THREAD

**Issue by ZaneBartlett1** [DartExplore/dallas-by-metro-backend#175]

**Comment by Nightwing52** [comment]
So, you mention in #128 filtering by rail time and the input would be a time but I think you also need a stationId because that travel time would be relative to a given station.

**Comment by ZaneBartlett1** [comment]
Good point, I updated the issue to reflect this

**Comment by Nightwing52** [comment]
I would also like to add since I filter walkingTime on the frontend that we shouldn't worry about it in this route.
