### ISSUE TITLE
Add lat and long to stationsDTO

### ISSUE THREAD

**Issue by ZaneBartlett1** [DartExplore/dallas-by-metro-backend#224]
So I want to create a tool that finds the nearest station to someone, as this tool doesn't seem to readily exist already. This could be done several ways 
- An API call from the front end that takes the current lat and long of someone, processes all of it on the backend, and returns the nearest station
- Creating a new DTO which just hands back the stations and their locations so that this can be processed on the front end and is a tighter API call
- Updating the current stationDTO (The route I'm going) so that it includes lat and long, so that it can be processed on the front end.

The reason for the third one is because currently our standard is to return all the attributes on an entity, and because I'd prefer client side processing so that it's clearer that we're not storing or doing anything extra with users location data.

**Comment by Nightwing52** [comment]
I would recommend the second options. We could make a DTO that holds stationId, lat, and long. Could be called StationLocation. The frontend can then just loop over them and find the closest one.

**Comment by ZaneBartlett1** [comment]
I mean I did quickly just update this but I don't mind going back. Why the second as opposed to the third though? Based on the other issue that I recently opened, I think it would make sense for our API to be more consistent when it comes to parameters and attributes. I think having us return all available attributes, and have parameters that filter against those attributes is the most intuitive. 

That's basically what we're doing in most cases anyway, the changes I suggest in that other issue are just formalizing that.

**Comment by Nightwing52** [comment]
Just like methods should have separation of concerns, DTOs should have them as well. It narrows the scope and makes sure we return only the needed data. Otherwise, all the other instances of retrieving stations will give us location data which most of the time isn't needed. Not a super big deal on this scale, but it's okay and often encouraged to have multiple DTOs per entity (we would just return entities in that case).

**Comment by ZaneBartlett1** [comment]
That makes sense, but I don't know that it's worth the complexity in this situation, as you mention it's not a big deal. If our API had a large load, it would make sense to limit it. In this case, I think the cleaner and better API design would be to return all attributes (which I know is basically like just returning the entity, which is typically not good form) and make it so that you can filter against those attributes in the parameters.

That doesn't make a lot of sense with lat and long, but if every other API call is doing that, then this would be the exception of something not returning it's full attributes, and I don't think it's worth it as an exception.

For reference I do understand the use cases for DTO. I do think we should actually consider making a second POI DTO because currently on stations we use our only POI DTO, which includes the station ID and name. This is redundant for our station calls though, because the Station DTO includes the ID and name.

So it's a balance with keeping our API consistent (returning all attributes and child attributes on an entity, which in almost all cases we are already doing that, given how simple our API is rn) vs trying to reduce the return load. I think in applications that are processing millions of calls in an hour the second one is much more worth doing, but in a simpler application like ours, intuitive and consistent returns are better.
